import Navigation from './components/Navigation'
import Script from "next/script";
import './globals.css'

export const metadata = {
  title: 'My first nextjs app',
  description: 'Generated by create next app',
  keywords: "next,react,app"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/quartz/bootstrap.min.css" />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></Script>
      </head>
      <body>
        <Navigation />
        <div className='container p-4'>
          {children}
        </div>
      </body>
      
    </html>
  )
}
